name: GCS Upload
run-name: ${{ github.actor }} is uploading to GCS 🚀
on:
    push:
      branches:
        - main
    workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
    contents: read
    packages: read

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'
        steps:
          - name: Checkout your repository using git
            uses: actions/checkout@v4
          - name: Setup Node
            uses: actions/setup-node@v4
          - name: Install & Build
            id: build
            shell: "bash"
            working-directory: astro-v1/
            run: |
                npm install
                npm run build
          - name: Authenticate with Google Cloud
            id: 'auth'
            uses: 'google-github-actions/auth@v2'
            with:
                credentials_json: '${{ secrets.GCS_CREDENTIALS }}'
                # project_id: 'slabby-xyz-site'
                # workload_identity_provider: 'projects/396362042427/locations/global/workloadIdentityPools/github/providers/slabby-xyz'
                    # 'projects/396362042427/locations/global/workloadIdentityPools/github'
                # projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
                # service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
          - name: Upload compiled files to GCS
            id: 'upload-folder'
            uses: 'google-github-actions/upload-cloud-storage@v2'
            with:
                path: 'astro-v1/dist'
                destination: 'slabby.xyz'
                parent: false